# Сервис для чтения книг

**Описание проекта**

Коронавирус застал мир врасплох, изменив привычный порядок вещей. В свободное время жители городов больше не выходят на улицу, не посещают кафе и торговые центры. Зато стало больше времени для книг. Это заметили стартаперы — и бросились создавать приложения для тех, кто любит читать. Ваша компания решила быть на волне и купила крупный сервис для чтения книг по подписке. 

Цель исследования - проанализировать базу данных сервиса для чтения книг по подписке.
В БД — информация о книгах, издательствах, авторах, а также пользовательские обзоры книг. Эти данные помогут сформулировать ценностное предложение для нового продукта.

**Описание данных**

Таблица `books` содержит данные о книгах:
- `book_id` — идентификатор книги;
- `author_id` — идентификатор автора;
- `title` — название книги;
- `num_pages` — количество страниц;
- `publication_date` — дата публикации книги;
- `publisher_id` — идентификатор издателя.

Таблица `authors` содержит данные об авторах:
- `author_id` — идентификатор автора;
- `author` — имя автора.

Таблица `publishers` содержит данные об издательствах:
- `publisher_id` — идентификатор издательства;
- `publisher` — название издательства;

Таблица `ratings` содержит данные о пользовательских оценках книг:
- `rating_id` — идентификатор оценки;
- `book_id` — идентификатор книги;
- `username` — имя пользователя, оставившего оценку;
- `rating` — оценка книги.

Таблица `reviews` содержит данные о пользовательских обзорах на книги:
- `review_id` — идентификатор обзора;
- `book_id` — идентификатор книги;
- `username` — имя пользователя, написавшего обзор;
- `text` — текст обзора.

**План проекта**
1. Описать цели исследования;
2. Исследовать таблицы;
3. Сдеалать SQL-запросы для каждого задания и вывести результаты:
    - Посчитать, сколько книг вышло после 1 января 2000 года;
    - Для каждой книги посчитать количество обзоров и среднюю оценку;
    - Определить издательство, которое выпустило наибольшее число книг толще 50 страниц;
    - Определить автора с самой высокой средней оценкой книг;
    - Посчитать среднее количество обзоров от пользователей, которые поставили больше 50 оценок.
4. Описать выводы по каждой из решённых задач.

## Обзор данных

In [1]:
# импортируем библиотеки
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# устанавливаем параметры
db_config = {'user': 'praktikum_student', # имя пользователя
             'pwd': 'Sdf4$2;d-d30pp', # пароль
             'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
             'port': 6432, # порт подключения
             'db': 'data-analyst-final-project-db'} # название базы данных

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(db_config['user'],
 db_config['pwd'],
 db_config['host'],
 db_config['port'],
 db_config['db'])

# сохраняем коннектор
engine = create_engine(connection_string, connect_args={'sslmode':'require'})

### Таблица `books`

In [3]:
query = '''
           SELECT *
           FROM books
        '''

pd.io.sql.read_sql(query, con = engine).head() # выведим первые строки

,book_id,author_id,title,num_pages,publication_date,publisher_id
0,1,546,'Salem's Lot,594,2005-11-01,93
1,2,465,1 000 Places to See Before You Die,992,2003-05-22,336
2,3,407,13 Little Blue Envelopes (Little Blue Envelope...,322,2010-12-21,135
3,4,82,1491: New Revelations of the Americas Before C...,541,2006-10-10,309
4,5,125,1776,386,2006-07-04,268

### Таблица `authors`

In [4]:
query = '''
           SELECT *
           FROM authors
        '''

pd.io.sql.read_sql(query, con = engine).head() # выведим первые строки

   author_id                          author
0          1                      A.S. Byatt
1          2  Aesop/Laura Harris/Laura Gibbs
2          3                 Agatha Christie
3          4                   Alan Brennert
4          5        Alan Moore/David   Lloyd

### Таблица `publishers`

In [5]:
query = '''
           SELECT *
           FROM publishers
        '''

pd.io.sql.read_sql(query, con = engine).head() # выведим первые строки

   publisher_id                          publisher
0             1                                Ace
1             2                           Ace Book
2             3                          Ace Books
3             4                      Ace Hardcover
4             5  Addison Wesley Publishing Company

### Таблица `ratings`

In [6]:
query = '''
           SELECT *
           FROM ratings
        '''

pd.io.sql.read_sql(query, con = engine).head() # выведим первые строки

   rating_id  book_id       username  rating
0          1        1     ryanfranco       4
1          2        1  grantpatricia       2
2          3        1   brandtandrea       5
3          4        2       lorichen       3
4          5        2    mariokeller       2

### Таблица `reviews`

In [7]:
query = '''
           SELECT *
           FROM reviews
        '''

pd.io.sql.read_sql(query, con = engine).head() # выведим первые строки

,review_id,book_id,username,text
0,1,1,brandtandrea,Mention society tell send professor analysis. ...
1,2,1,ryanfranco,Foot glass pretty audience hit themselves. Amo...
2,3,2,lorichen,Listen treat keep worry. Miss husband tax but ...
3,4,3,johnsonamanda,Finally month interesting blue could nature cu...
4,5,3,scotttamara,Nation purpose heavy give wait song will. List...

## Запросы к базе данных

### 1. Кол-во книг, выпущенных после 1 января 2000 года

In [8]:
query = '''
            SELECT COUNT (DISTINCT book_id) as cnt
            FROM books
            WHERE publication_date > '2000-01-01'
'''
pd.io.sql.read_sql(query, con = engine)

   cnt
0  819

**Вывод**: после 1 января 2000 года вышло всего 819 книг

### 2. Количество обзоров и средняя оценка для каждой книги

In [9]:
query = '''
            SELECT books.book_id,
                    books.title,
                    count(distinct reviews.review_id) as cnt_rev,
                    round(avg(ratings.rating), 2) as avg_rat
            FROM books
            left join reviews on reviews.book_id = books.book_id
            left join ratings on ratings.book_id = books.book_id
            GROUP BY books.book_id
            ORDER BY cnt_rev desc, avg_rat desc
'''
pd.io.sql.read_sql(query, con = engine)

,book_id,title,cnt_rev,avg_rat
0,948,Twilight (Twilight #1),7,3.66
1,302,Harry Potter and the Prisoner of Azkaban (Harr...,6,4.41
2,299,Harry Potter and the Chamber of Secrets (Harry...,6,4.29
3,656,The Book Thief,6,4.26
4,734,The Glass Castle,6,4.21
...,...,...,...,...
995,191,Disney's Beauty and the Beast (A Little Golden...,0,4.00
996,387,Leonardo's Notebooks,0,4.00
997,221,Essential Tales and Poems,0,4.00
998,83,Anne Rice's The Vampire Lestat: A Graphic Novel,0,3.67
999,808,The Natural Way to Draw,0,3.00

**Вывод**: больше всего обзоров сделано на книгу Twilight, у 6 книг нет обзоров, самый высокий средний рейтинг (5.00) у 44 книг

### 3. Издательство, которое выпустило наибольшее число книг толще 50 страниц

In [10]:
query = '''
            SELECT publishers.publisher,
            count(books.book_id) as cnt_books
            FROM books
            left join publishers on publishers.publisher_id = books.publisher_id
            WHERE books.num_pages > 50
            GROUP BY publishers.publisher
            ORDER BY cnt_books desc
            LIMIT 1
'''
pd.io.sql.read_sql(query, con = engine)

       publisher  cnt_books
0  Penguin Books         42

**Вывод**: больше всего книг (42 шт) выпустило издательство Penguin Books - это довольно большое и старое издательство 

### 4. Автор с самой высокой средней оценкой книг (только книги с 50 и более оценками)

In [11]:
query = '''
            SELECT authors.author,
            round(avg(ratings.rating),3) as avg_rat
            FROM books
            left join authors on authors.author_id = books.author_id
            left join ratings on ratings.book_id = books.book_id
            WHERE books.book_id IN (
                    SELECT book_id
                    FROM ratings
                    GROUP BY book_id
                    HAVING count(rating_id) >= 50
                    ORDER BY count(rating_id) desc)
            GROUP BY authors.author
            ORDER BY avg_rat desc
            LIMIT 1
'''
pd.io.sql.read_sql(query, con = engine)

                       author  avg_rat
0  J.K. Rowling/Mary GrandPré    4.287

**Вывод:** самая высокая средняя оценка книг у автора Дж.К. Роулинг. Средняя оценка ее книг составляет 4.287

### 5. Среднее количество обзоров от пользователей, которые поставили больше 50 оценок

In [12]:
query = '''
            SELECT round(avg(review_cnt)) as cnt_rev
            FROM (
                SELECT username,
                count(review_id) as review_cnt
                FROM reviews
                WHERE username IN (
                                    SELECT username
                                    FROM ratings
                                    GROUP BY username
                                    HAVING count(rating_id) > 50)
                GROUP BY username
                ) as rev_count
'''
pd.io.sql.read_sql(query, con = engine)

   cnt_rev
0     24.0

**Вывод:** пользователи, поставившие более 50 оценок, в среднем пишут по 24 обзора

## Общий вывод
В результате анализа БД сервиса для чтения книг были получены следующие результаты:

1. В БД содержится информация о 1000 книг
2. Около 82% книг выпущены за последние 1 января 2000 года (819 шт)
3. Практичекси все книги имеют обзоры и оценки
4. Больше всего обзоров сделано на книгу Twilight - 7 шт
5. Издательство, которое выпустило больше всего книг - Penguin Books. Оно выпустило 42 книги (примерно 4% из всего кол-ва)
6. Самые высокие средние оценки у автора Дж.К.Роулинг - 4.287 балла.
7. В среднем, пользователи, поставившие более 50 оценок, пишут по 24 обзора